#!/usr/bin/env bash
# Resolves a changed source file path to its compact diff artifact path
# using diff_artifacts_map.tsv generated by collect_infra_diff.sh.

set -euo pipefail

usage() {
  cat >&2 <<EOF
Usage:
  resolve_diff_artifact.sh <output_dir> <source_file_path>

Example:
  resolve_diff_artifact.sh copilot/qa_review/tmp lib/infrastructure/core/service/base_service_module/service_module.dart
EOF
}

if [[ $# -ne 2 ]]; then
  usage
  exit 1
fi

output_dir="$1"
source_file="$2"
map_file="$output_dir/diff_artifacts_map.tsv"

if [[ ! -f "$map_file" ]]; then
  echo "Error: map file not found: $map_file" >&2
  echo "Run collect_infra_diff.sh first." >&2
  exit 1
fi

artifact_name="$({
  awk -F '\t' -v target="$source_file" '$1 == target { print $2; found=1; exit } END { if (!found) exit 1 }' "$map_file"
} || true)"

if [[ -z "$artifact_name" ]]; then
  echo "Error: source path not found in map: $source_file" >&2
  exit 1
fi

artifact_path="$output_dir/diffs/$artifact_name"
if [[ ! -f "$artifact_path" ]]; then
  echo "Error: mapped artifact missing: $artifact_path" >&2
  exit 1
fi

printf '%s\n' "$artifact_path"
